### PR TITLE
Enable Github pages docs deploy

### PR DESCRIPTION
**Pull request by jonathanstallings**
Addresses issue #22 

Previous settings were trying to serve from `master` branch `/docs` folder instead of the prepared site folder. Github pages settings are fairly constrained as to which folders to serve from.

See: https://help.github.com/articles/user-organization-and-project-pages/

I've opted for including a new Makefile target, `make gh-deploy` which uses `mkdocs gh-deploy` to  build onto a `gh-pages` branch and serve from there.

### CODE REVIEW

**Comment by jonathanstallings** [comment]
Note that we may want to exclude the `gh-pages` branch from standard ci tests, as it only contains mkdocs-built documentation.

**Comment by zpatrick** [comment]
jonathanstallings: could you get this working with the `master /docs` setup? It would be nice to not have to change our branching and release strategy if possible.

**Comment by jonathanstallings** [comment]
Thanks @zpatrick. I'll rip out all the IMS-specific stuff for docs and reorganize to serve from `master` branch `/docs`.

**Comment by jonathanstallings** [comment]
Closed in favor of fix serving from `master` branch `/docs`.

**Pull request closed without merging**
