### PR TITLE
add initial Windows documentation / support

### PR DESCRIPTION
**Pull request by diemonster**

### CODE REVIEW

**Comment by sesh-kebab** [comment]
Looks good. The recommended size in the Amazon walkthrough for volumes seems to be 200Gb. But 128Gb if probably fine too I guess.

**Comment by diemonster** [comment]
@sesh-kebab Ahhh good call, if they recommend 200gb I will change.

**Comment by sesh-kebab** [comment]
Also, I think it would be better to pass in the userdata when creating the environment to avoid having to manually copy the cluster name over. I.e.,

```
<powershell>
## The string 'windows' should be replaced with your cluster name

# Set agent env variables for the Machine context (durable)
$clusterName = {{ .ECSEnvironmentID }}
Write-Host Cluster name set as: $clusterName -foreground green

[Environment]::SetEnvironmentVariable("ECS_CLUSTER", $clusterName, "Machine")
```

**Comment by zpatrick** [comment]
Would it be better to add a `windows` example to https://github.com/quintilesims/layer0-examples?

**Comment by diemonster** [comment]
@zpatrick not a bad idea, it does seem strange to put this where it currently sits. I'll move the stuff and close this PR.

**Pull request closed without merging**
